### ISSUE TITLE
Create map storage

### ISSUE THREAD

**Issue by Samuelmorris** [alephnulltho/Saluki-Platformer#5]
We need to decide how map information is stored and structured, like in a text file.

**Comment by lasagnamassage** [comment]
Gotcha. I've discovered a way using JavaScript's XMLHTTPRequest object once we have the game up on a server (level files would be stored there). We could also alternatively use a Java Applet or PHP to do the file manipulation, but these ways have cons that outweigh the pros in my opinion. But until we decide, for the sake of simplicity I'm setting up a lexical analyzer and parser to convert text files into working layouts for the game (these can still be used after we transition to XMLHTTPRequest with minor editing).
